site_name: Teachable Machine Package - Documentation

theme:
  name: "readthedocs"

plugins:
  - mkdocstrings

nav:
  - Teachable Machine - Home: index.md
  - How-To Guide: how-to-guide.md
  - Requirements: requirements.md
  - Code Examples: codeExamples.md
  - Explanation: explanation.md
  - Contributing: contribution.md
